# This is default sample specification
# Feel free to change it
# Call ecpdf showdoc pluginspec to see the list of available fields and their description
pluginName: EC-TOPdesk
description: ElectricFlow integration with TOPdesk
version: 1.0.0
author: L. Rochette
authorUrl: mailto:lrochette@electric-cloud.com
category: Resource Management

procedures:
- name: createIncident
  description: Create a new incident
  steps:
  -
  name: createIncident
  shell: ec-perl
  hasConfig: true
  parameters:
  - name: microservice
    documentation: The name of the microservice
    type: entry
    required: true
    label: Microservice name
  - name: environment
    documentation: The name of the environment
    type: entry
    required: true
    label: Environment name
  - name: process
    documentation: The name of the process
    type: entry
    required: true
    label: Process name
  - name: url
    documentation: URL pointing to the failed job
    type: entry
    required: true
    label: url
  - name: operatorGroupId
    documentation: ID of the TOPdesk operator group to assign the incident to
    type: entry
    required: true
    label: operatorGroupId
  - name: externalNumber
    documentation: External number referring to the failed job to show in TOPdesk
    type: entry
    required: true
    label: externalNumber
  outputParameters:
      incident: JSON representation of the created incident
      incidentId: Incident ID of the created incident
  # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
  shell: ec-perl
- name: createOperatorChange
  description: Create a new change for an operator
  steps:
  -
  name: createOperatorChange
  shell: ec-perl
  hasConfig: true
  parameters:
  - name: pipelineJob
    documentation: The name of the pipeline job
    type: entry
    required: true
    label: Name of the pipeline job
  - name: url
    documentation: URL pointing to the Pipeline job requesting approval
    type: entry
    required: true
    label: url
  - name: templateNumber
    documentation: Number of the Change Template to apply when creating the Request for Change in TOPdesk
    type: entry
    required: true
    label: templateNumber
  - name: externalNumber
    documentation: External number referring to the failed job to show in TOPdesk
    type: entry
    required: true
    label: externalNumber
  outputParameters:
      change: JSON representation of the created operator change
      changeId: Change ID of the created operator change
  # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
  shell: ec-perl

- name: getOperatorChange
  description: Get an operator change record
  steps:
  -
  name: getOperatorChange
  shell: ec-perl
  hasConfig: true
  parameters:
  - name: changeId
    documentation: the ID of the operator change
    type: entry
    required: true
    label: Operator change ID
  outputParameters:
      change: JSON representation of the operator change

- name: approveOrRejectPipelineGate
  description: Approve or Reject the Pipeline
  steps:
  -
  name: approveOrRejectPipelineGate
  shell: ec-perl
  hasConfig: false
  parameters:
  - name: action
    documentation: "Action: either 1 (approve) or 0 (reject)"
    type: entry
    required: true
    label: Action

# This is a declaration for the plugin configuration
configuration:
  # Shell to be used for checking connection
  shell: ec-perl
  parameters:
   - name: config
     type: entry
     label: Configuration Name
     required: true
     documentation: The name for the created configuration.
   - name: desc
     type: entry
     label: Description
     required: false
     documentation: Description for the configuration.
   - name: endpoint
     label: Endpoint
     type: entry
     required: true
     documentation: TOPdesk instance endpoint to connect to.
   - name: credential
     type: credential
     label: Credential
     userNameLabel: Username
     required: true
     passwordLabel: Password
   - name: checkConnection
     label: Check Connection?
     type: checkbox
     checkedValue: true
     uncheckedValue: false
     initiallyChecked: 1
   - name: callerId
     type: entry
     label: callerId
     required: true
     documentation: Id of the caller in TOPdesk to whom all created incidents and changes are assigned.
   - name: processingStatusId
     type: entry
     label: processingStatusId
     required: false
     documentation: Id of the processingStatus for incidents created in TOPdesk
   - name: subcategoryId
     type: entry
     label: subcategoryId
     required: false
     documentation: Id of the the subcategory for the incidents created in TOPdesk
   - name: debugLevel
     # This parameter name "debugLevel" is supported by ECPDF Logger out of the box
     label: Debug Level
     type: select
     required: 0
     value: 0
     options:
       - name: Info
         value: 0
       - name: Debug
         value: 1
       - name: Trace
         value: 2
